# -*- coding: utf-8 -*-
"""linear regression project 04-11-2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RI1OH3bsCXn0n-S6FOQjTWDZCot5Wf7q
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.linear_model import LinearRegression

df = pd.read_csv('/insurance.csv')

df

df.head()

df.info()

df.describe() # statistical summary of the data

plt.figure(figsize = (12,5))

sns.histplot(df['bmi'],kde = True)
plt.title("BMI distribution with KDE")
plt.xlabel("BMI")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize = (10,4))
sns.boxplot(x = df['bmi'])
plt.title("BMI distribution with KDE")
plt.show()

#remove the outliers

Q1 = df['bmi'].quantile(0.25)
Q3 = df['bmi'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f"lower : {lower_bound}, upper : {upper_bound}")


df = df[(df['bmi'] >= lower_bound) & (df['bmi'] <= upper_bound)]

df.drop_duplicates(inplace = True)

# clippng the outliers
df_cleaned = df[(df ['bmi']>= lower_bound) & (df['bmi'] <= upper_bound)]

plt.figure(figsize = (12,5))

sns.histplot(df_cleaned['bmi'],kde = True)
plt.title("BMI distribution with KDE")
plt.xlabel("BMI")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize = (10,4))
sns.boxplot(x = df_cleaned['bmi'])
plt.title("BMI distribution with KDE")
plt.show()

df_cleaned

# one hot encoding
df_cleaned =pd.get_dummies(df_cleaned,drop_first = True)
df_cleaned

plt.figure(figsize = (12,5))
sns.heatmap(df_cleaned.corr(),annot = True)

# feature enginnering
df_cleaned.columns

x = df_cleaned[["age","bmi","smoker_yes"]]
y  = df_cleaned["charges"]

# train test split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 23)

#train the model

model = LinearRegression()
model.fit(x_train,y_train)

y_pred = model.predict(x_test)   # testing on test data
y_train_pred = model.predict(x_train) # testing on train

print(f'testing results : {r2_score(y_test,y_pred)}')
print(f'training results : {r2_score(y_train,y_train_pred)}')

# print mean squard error
print(f'testing results : {mean_squared_error(y_test,y_pred)}')
print(f'training results : {mean_squared_error(y_train,y_train_pred)}')

# how to save the model?
import pickle
with open ("best_model.pkl","wb") as f:
    pickle.dump(model,f)

